// courses_v2.js
// Combined SFU (earlier) and UBC coursework in chronological order
// This corrected file includes all non-transfer courses from your transcript.
// Fields follow the schema: title, categories, summary, description (empty array), technologies (empty array if none), start_date, end_date, github_url, live_url, org_url, importance

const courses = [
  // --- SFU coursework (2019 - 2021) ---
  {
    title: "BISC 102: General Biology",
    categories: [],
    summary: "Introductory biology covering cell structure, genetics, and organismal biology with laboratory investigation experience.",
    description: [],
    technologies: [],
    start_date: new Date(2019, 8),
    end_date: new Date(2019, 11),
    github_url: null,
    live_url: null,
    org_url: null,
    importance: 1
  },
  {
    title: "CHEM 121: General Chemistry I (with Lab)",
    categories: [],
    summary: "Fundamental chemistry concepts and laboratory techniques including atomic structure, bonding, and stoichiometry.",
    description: [],
    technologies: [],
    start_date: new Date(2019, 8),
    end_date: new Date(2019, 11),
    github_url: null,
    live_url: null,
    org_url: null,
    importance: 1
  },
  {
    title: "ECON 103: Principles of Microeconomics",
    categories: [],
    summary: "Microeconomic principles covering supply/demand, market structures, and optimization useful for analytical decision-making.",
    description: [],
    technologies: [],
    start_date: new Date(2019, 8),
    end_date: new Date(2019, 11),
    github_url: null,
    live_url: null,
    org_url: null,
    importance: 2
  },
  {
    title: "CHEM 122: General Chemistry II",
    categories: [],
    summary: "Continuation of General Chemistry I, focusing on thermodynamics, kinetics, and chemical equilibria with lab practice.",
    description: [],
    technologies: [],
    start_date: new Date(2020, 0),
    end_date: new Date(2020, 3),
    github_url: null,
    live_url: null,
    org_url: null,
    importance: 1
  },
  {
    title: "ECON 105: Principles of Macroeconomics",
    categories: [],
    summary: "Macroeconomic theory and policy fundamentals such as GDP, inflation, and monetary policy for high-level economic analysis.",
    description: [],
    technologies: [],
    start_date: new Date(2020, 0),
    end_date: new Date(2020, 3),
    github_url: null,
    live_url: null,
    org_url: null,
    importance: 2
  },
  {
    title: "MATH 154: Calculus I for Biological Sciences",
    categories: [],
    summary: "Single-variable calculus focused on derivatives and applications relevant to biological modelling and analysis.",
    description: [],
    technologies: [],
    start_date: new Date(2020, 0),
    end_date: new Date(2020, 3),
    github_url: null,
    live_url: null,
    org_url: null,
    importance: 2
  },
  {
    title: "PHYS 101: Physics for Life Sciences I",
    categories: [],
    summary: "Introductory physics covering mechanics with applications to life sciences and quantitative problem solving.",
    description: [],
    technologies: [],
    start_date: new Date(2020, 0),
    end_date: new Date(2020, 3),
    github_url: null,
    live_url: null,
    org_url: null,
    importance: 1
  },
  {
    title: "BISC 101: General Biology",
    categories: [],
    summary: "Foundational biology topics reinforcing core concepts in cellular and organismal biology with lab work.",
    description: [],
    technologies: [],
    start_date: new Date(2020, 4),
    end_date: new Date(2020, 7),
    github_url: null,
    live_url: null,
    org_url: null,
    importance: 1
  },
  {
    title: "MATH 155: Calculus II for Biological Sciences",
    categories: [],
    summary: "Continued calculus with integration techniques and applications to biological models and quantitative reasoning.",
    description: [],
    technologies: [],
    start_date: new Date(2020, 4),
    end_date: new Date(2020, 7),
    github_url: null,
    live_url: null,
    org_url: null,
    importance: 2
  },
  {
    title: "PHYS 102: Physics for Life Sciences II",
    categories: [],
    summary: "Second-term physics topics including waves and thermodynamics with laboratory components applicable to experimental work.",
    description: [],
    technologies: [],
    start_date: new Date(2020, 4),
    end_date: new Date(2020, 7),
    github_url: null,
    live_url: null,
    org_url: null,
    importance: 1
  },
  {
    title: "BISC 202: Genetics",
    categories: [],
    summary: "Genetics principles including Mendelian inheritance, molecular genetics, and applications to biological data interpretation.",
    description: [],
    technologies: [],
    start_date: new Date(2020, 8),
    end_date: new Date(2020, 11),
    github_url: null,
    live_url: null,
    org_url: null,
    importance: 1
  },
  {
    title: "CMPT 120: Intro to Computing/Programming I",
    categories: ["SWE"],
    summary: "Introduction to programming fundamentals, algorithmic thinking, and problem solving using an imperative programming language.",
    description: [],
    technologies: ["Python"],
    start_date: new Date(2020, 8),
    end_date: new Date(2020, 11),
    github_url: null,
    live_url: null,
    org_url: null,
    importance: 4
  },
  {
    title: "MACM 101: Discrete Mathematics I",
    categories: ["Theory"],
    summary: "Discrete math foundations including logic, proofs, set theory and combinatorics essential for theoretical CS.",
    description: [],
    technologies: [],
    start_date: new Date(2020, 8),
    end_date: new Date(2020, 11),
    github_url: null,
    live_url: null,
    org_url: null,
    importance: 3
  },
  {
    title: "STAT 201: Statistics for Life Sciences (withdrawn)",
    categories: [],
    summary: null,
    description: [],
    technologies: [],
    start_date: new Date(2020, 8),
    end_date: new Date(2020, 11),
    github_url: null,
    live_url: null,
    org_url: null,
    importance: 1
  },
  {
    title: "CHEM 280: Organic Chemistry I",
    categories: [],
    summary: "Foundations of organic chemistry including structure, mechanism, and reaction types important for laboratory sciences.",
    description: [],
    technologies: [],
    start_date: new Date(2021, 0),
    end_date: new Date(2021, 3),
    github_url: null,
    live_url: null,
    org_url: null,
    importance: 1
  },
  {
    title: "CMPT 125: Intro to Computing/Programming II",
    categories: ["SWE"],
    summary: "Object-oriented programming and software design fundamentals, reinforcing data structures and modular coding practices.",
    description: [],
    technologies: ["Java"],
    start_date: new Date(2021, 0),
    end_date: new Date(2021, 3),
    github_url: null,
    live_url: null,
    org_url: null,
    importance: 4
  },
  {
    title: "CMPT 127: Computing Laboratory",
    categories: ["SWE"],
    summary: "Practical programming lab focusing on project-based exercises to apply programming and debugging techniques.",
    description: [],
    technologies: ["Java", "Git"],
    start_date: new Date(2021, 0),
    end_date: new Date(2021, 3),
    github_url: null,
    live_url: null,
    org_url: null,
    importance: 4
  },
  {
    title: "MBB 222: Molecular Biology & Biochemistry",
    categories: [],
    summary: "Fundamentals of molecular biology and biochemical techniques with an emphasis on experimental interpretation.",
    description: [],
    technologies: [],
    start_date: new Date(2021, 0),
    end_date: new Date(2021, 3),
    github_url: null,
    live_url: null,
    org_url: null,
    importance: 1
  },

  // --- UBC coursework (2021 - 2025) ---
  {
    title: "CPSC 210: Software Construction",
    categories: ["SWE"],
    summary: "Software engineering fundamentals: object-oriented design, testing, version control and build tools with Java projects.",
    description: [],
    technologies: ["Java", "Git", "JUnit", "Maven"],
    start_date: new Date(2021, 8),
    end_date: new Date(2021, 11),
    github_url: null,
    live_url: null,
    org_url: null,
    importance: 5
  },
  {
    title: "ENGL 110: Approaches to Literature",
    categories: [],
    summary: null,
    description: [],
    technologies: [],
    start_date: new Date(2021, 8),
    end_date: new Date(2021, 11),
    github_url: null,
    live_url: null,
    org_url: null,
    importance: 1
  },
  {
    title: "MATH 200: Calculus III",
    categories: [],
    summary: null,
    description: [],
    technologies: [],
    start_date: new Date(2021, 8),
    end_date: new Date(2021, 11),
    github_url: null,
    live_url: null,
    org_url: null,
    importance: 2
  },
  {
    title: "STAT 251: Elementary Statistics",
    categories: ["ML"],
    summary: null,
    description: [],
    technologies: [],
    start_date: new Date(2021, 8),
    end_date: new Date(2021, 11),
    github_url: null,
    live_url: null,
    org_url: null,
    importance: 3
  },
  {
    title: "CPSC 213: Introduction to Computer Systems",
    categories: ["Systems", "SWE"],
    summary: "Systems-level programming and architecture: C programming, assembly, memory layout and debugging for performance and reliability.",
    description: [],
    technologies: ["C", "Assembly", "Linux", "GDB"],
    start_date: new Date(2022, 0),
    end_date: new Date(2022, 3),
    github_url: null,
    live_url: null,
    org_url: null,
    importance: 5
  },
  {
    title: "CPSC 221: Basic Algorithms and Data Structures",
    categories: ["SWE", "Theory"],
    summary: "Core data structures and algorithmic techniques with focus on complexity analysis and practical implementation.",
    description: [],
    technologies: ["C++", "Java"],
    start_date: new Date(2022, 0),
    end_date: new Date(2022, 3),
    github_url: null,
    live_url: null,
    org_url: null,
    importance: 5
  },
  {
    title: "MATH 221: Matrix Algebra",
    categories: ["Theory"],
    summary: null,
    description: [],
    technologies: [],
    start_date: new Date(2022, 0),
    end_date: new Date(2022, 3),
    github_url: null,
    live_url: null,
    org_url: null,
    importance: 2
  },
  {
    title: "WRDS 150: Writing and Research in the Disciplines",
    categories: [],
    summary: null,
    description: [],
    technologies: [],
    start_date: new Date(2022, 0),
    end_date: new Date(2022, 3),
    github_url: null,
    live_url: null,
    org_url: null,
    importance: 1
  },
  {
    title: "CPSC 310: Introduction to Software Engineering",
    categories: ["SWE"],
    summary: "Software engineering practices including design, testing, code review and team development workflows preparing students for collaborative engineering roles.",
    description: [],
    technologies: ["Git", "Agile", "UML", "CI"],
    start_date: new Date(2022, 8),
    end_date: new Date(2022, 11),
    github_url: null,
    live_url: null,
    org_url: null,
    importance: 5
  },
  {
    title: "CPSC 317: Internet Computing",
    categories: ["SWE", "DevOps"],
    summary: "Client-server and web fundamentals: HTTP, REST, and building web applications and services with practical implementation experience.",
    description: [],
    technologies: ["HTTP", "JavaScript", "Databases"],
    start_date: new Date(2022, 8),
    end_date: new Date(2022, 11),
    github_url: null,
    live_url: null,
    org_url: null,
    importance: 4
  },
  {
    title: "CPSC 320: Intermediate Algorithm Design and Analysis",
    categories: ["Theory", "SWE"],
    summary: "Advanced algorithmic techniques (greedy, DP, graphs) for designing efficient solutions to complex computational problems.",
    description: [],
    technologies: ["C++", "Python"],
    start_date: new Date(2022, 8),
    end_date: new Date(2022, 11),
    github_url: null,
    live_url: null,
    org_url: null,
    importance: 5
  },
  {
    title: "CPSC 322: Introduction to Artificial Intelligence",
    categories: ["ML", "AI"],
    summary: "Introductory AI topics including search, planning, and knowledge representation with practical problem-solving applications.",
    description: [],
    technologies: ["Python"],
    start_date: new Date(2022, 8),
    end_date: new Date(2022, 11),
    github_url: null,
    live_url: null,
    org_url: null,
    importance: 4
  },
  {
    title: "CPSC 304: Introduction to Relational Databases",
    categories: ["DB", "SWE"],
    summary: "Relational database design and querying with SQL, normalization and schema design for robust data storage and retrieval.",
    description: [],
    technologies: ["SQL", "PostgreSQL"],
    start_date: new Date(2023, 0),
    end_date: new Date(2023, 3),
    github_url: null,
    live_url: null,
    org_url: null,
    importance: 5
  },
  {
    title: "CPSC 313: Computer Hardware and Operating Systems",
    categories: ["Systems", "SWE"],
    summary: "Hardware and OS principles covering concurrency, memory hierarchy, and system performance considerations for systems development.",
    description: [],
    technologies: ["C", "Linux", "Assembly"],
    start_date: new Date(2023, 0),
    end_date: new Date(2023, 3),
    github_url: null,
    live_url: null,
    org_url: null,
    importance: 5
  },
  {
    title: "CPSC 319: Software Engineering Project",
    categories: ["SWE", "DevOps"],
    summary: "Team-based software project delivering full-stack development experience, collaboration, deployment and project management skills.",
    description: [],
    technologies: ["Git", "CI/CD", "Docker", "Web frameworks"],
    start_date: new Date(2023, 0),
    end_date: new Date(2023, 3),
    github_url: null,
    live_url: null,
    org_url: null,
    importance: 5
  },
  {
    title: "ECON 323: Quantitative Economic Modelling with Data Science Applications",
    categories: ["Data Science"],
    summary: "Applied quantitative modelling and data analysis techniques for economic problems using statistical and programming tools.",
    description: [],
    technologies: ["R", "Python"],
    start_date: new Date(2023, 0),
    end_date: new Date(2023, 3),
    github_url: null,
    live_url: null,
    org_url: null,
    importance: 3
  },
  {
    title: "CPSC 298: Co-operative Work Placement I",
    categories: ["SWE"],
    summary: "Work placement in a professional environment providing hands-on experience with development workflows and team processes.",
    description: [],
    technologies: ["Git"],
    start_date: new Date(2023, 8),
    end_date: new Date(2023, 11),
    github_url: null,
    live_url: null,
    org_url: null,
    importance: 5
  },
  {
    title: "CPSC 340: Machine Learning and Data Mining",
    categories: ["ML", "Data Science"],
    summary: "Foundational machine learning and data-mining techniques with a focus on applied modelling, evaluation and feature engineering.",
    description: [],
    technologies: ["Python", "scikit-learn", "pandas", "NumPy"],
    start_date: new Date(2024, 0),
    end_date: new Date(2024, 3),
    github_url: null,
    live_url: null,
    org_url: null,
    importance: 5
  },
  {
    title: "CPSC 436S: Cybersecurity",
    categories: ["SWE", "CyberSecurity", "Systems", "DevOps"],
    summary: "Hands-on cybersecurity topics including web/server security, vulnerability analysis, network exploitation, scripting, and capture-the-flag labs preparing students for defensive and offensive security roles.",
    description: [],
    technologies: ["Python", "JavaScript", "Bash", "Cryptography", "SQL Injection", "HTTPS", "Assembly", "Wireshark", "Ghidra"],
    start_date: new Date(2024, 0),
    end_date: new Date(2024, 3),
    github_url: null,
    live_url: null,
    org_url: null,
    importance: 5
  },
  {
    title: "SOCI 200: Sociology of Family",
    categories: [],
    summary: null,
    description: [],
    technologies: [],
    start_date: new Date(2024, 0),
    end_date: new Date(2024, 3),
    github_url: null,
    live_url: null,
    org_url: null,
    importance: 1
  },
  {
    title: "COMR 457: Fundamentals of Financial Accounting",
    categories: [],
    summary: 'Introduces financial accounting principles, focusing on interpreting and analyzing financial statements to inform data-driven business and investment decisions',
    description: [],
    technologies: [],
    start_date: new Date(2024, 8),
    end_date: new Date(2024, 11),
    github_url: null,
    live_url: null,
    org_url: null,
    importance: 2
  },
  {
    title: "CPSC 330: Applied Machine Learning",
    categories: ["ML", "Data Science"],
    summary: "Applied ML focusing on end-to-end modelling, feature engineering and interpretability using industry tools.",
    description: [],
    technologies: ["Python", "scikit-learn", "Jupyter", "pandas"],
    start_date: new Date(2024, 8),
    end_date: new Date(2024, 11),
    github_url: null,
    live_url: null,
    org_url: null,
    importance: 5
  },
  {
    title: "CPSC 430: Computers and Society",
    categories: [],
    summary: null,
    description: [],
    technologies: [],
    start_date: new Date(2024, 8),
    end_date: new Date(2024, 11),
    github_url: null,
    live_url: null,
    org_url: null,
    importance: 1
  },
  {
    title: "COMM 280: Entrepreneurship",
    categories: [],
    summary: 'Explores the entrepreneurial process from ideation to venture launch, emphasizing opportunity evaluation, market validation, and the fundamentals of business model design',
    description: [],
    technologies: [],
    start_date: new Date(2024, 8),
    end_date: new Date(2024, 11),
    github_url: null,
    live_url: null,
    org_url: null,
    importance: 2
  },
  {
    title: "CPSC 416: Distributed Systems",
    categories: ["SWE", "DevOps", "Systems"],
    summary: "Distributed systems principles including fault tolerance, consensus protocols, replication and consistency for resilient services.",
    description: [],
    technologies: ["Distributed systems concepts", "RPC", "consensus protocols", "Docker"],
    start_date: new Date(2025, 0),
    end_date: new Date(2025, 3),
    github_url: null,
    live_url: null,
    org_url: null,
    importance: 5
  },
  {
    title: "CPSC 440: Advanced Machine Learning",
    categories: ["ML"],
    summary: "Advanced machine learning topics such as deep learning, probabilistic models and scalable learning techniques.",
    description: [],
    technologies: ["Python", "PyTorch", "TensorFlow", "probabilistic models"],
    start_date: new Date(2025, 0),
    end_date: new Date(2025, 3),
    github_url: null,
    live_url: null,
    org_url: null,
    importance: 5
  },
  {
    title: "FMST 314: Relationship Development",
    categories: [],
    summary: null,
    description: [],
    technologies: [],
    start_date: new Date(2025, 0),
    end_date: new Date(2025, 3),
    github_url: null,
    live_url: null,
    org_url: null,
    importance: 1
  }
];

export { courses };
